### ISSUE TITLE
[windows] File system "permission denied"

### ISSUE THREAD

**Issue by DoLife** [AntonOsika/gpt-engineer#134]
I downloaded the new repo today, and when running a prompt i receive the following error.
It worked fine last night on the old repo of the previous day.
I have full administrative rights.

Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\Admin\Github\gpt-engineer\gpt_engineer\main.py", line 49, in <module>
    app()

  File "C:\Users\Admin\Github\gpt-engineer\gpt_engineer\main.py", line 45, in chat
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "C:\Users\Admin\Github\gpt-engineer\gpt_engineer\steps.py", line 129, in gen_code
    to_files(messages[-1]["content"], dbs.workspace)

  File "C:\Users\Admin\Github\gpt-engineer\gpt_engineer\chat_to_files.py", line 29, in to_files
    workspace[file_name] = file_content
    ~~~~~~~~~^^^^^^^^^^^

  File "C:\Users\Admin\Github\gpt-engineer\gpt_engineer\db.py", line 20, in __setitem__
    with open(self.path / key, 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Admin\\Github\\gpt-engineer\\my-new-project\\workspace'

**Comment by jtac** [comment]
Same issue (not working as adming but still, permission denied in my own directory)

´´´
│ ❱ 20 │   │   with open(self.path / key, 'w', encoding='utf-8') as f:                             │
│   21 │   │   │   f.write(val)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\NN\\gpt-engineer\\project1\\workspace'
´´´

**Comment by AntonOsika** [comment]
Closing this as it's related to your setup, not GPT Engineer!

FYI @patillacode

**Comment by jtac** [comment]
Well, tbh, if you have a normally functioning environment (dozens of successfully checked out and ran python projects), and you follow the instructions to the letter and get an error, perhaps at least the instructions need updating?

**Comment by AntonOsika** [comment]
Opened again. 

Would you be able to run the tests on your computer and see if they pass? And if they do, try to write a test that gives the same error? Thanks
