### ISSUE TITLE
Pytest endpoint doen't include window

### ISSUE THREAD

**Issue by girijeshcse** [AntonOsika/gpt-engineer#159]
I m getting this pytest error for every project I create, looks like windows part need to be added ?

To run the unit tests, use the following command:

```
pytest
```
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\hp\Documents\gpt-engineer\gpt_engineer\main.py", line 59, in <module>
    app()

  File "C:\Users\hp\Documents\gpt-engineer\gpt_engineer\main.py", line 54, in chat
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "C:\Users\hp\Documents\gpt-engineer\gpt_engineer\steps.py", line 174, in gen_entrypoint
    assert lang in [
           ^^^^^^^^^

AssertionError: Generated entrypoint command that was not bash

**Comment by patillacode** [comment]
If you wish to reopen the issue please do following the new issue template.
