### ISSUE TITLE
Python compile error with latest main

### ISSUE THREAD

**Issue by roderik** [AntonOsika/gpt-engineer#164]
It worked with a version this afternoon, but now it dies with 

```
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/Users/roderik/Development/gpt-engineer/gpt_engineer/main.py", line 63, in <module>
    app()

  File "/Users/roderik/Development/gpt-engineer/gpt_engineer/main.py", line 58, in chat
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "/Users/roderik/Development/gpt-engineer/gpt_engineer/steps.py", line 61, in gen_spec
    ai.fsystem(f"Instructions: {dbs.input['main_prompt']}"),
                                ~~~~~~~~~^^^^^^^^^^^^^^^

  File "/Users/roderik/Development/gpt-engineer/gpt_engineer/db.py", line 21, in __getitem__
    raise KeyError(key)

KeyError: 'main_prompt'
```

**Comment by roderik** [comment]
Never mind, the projects folder is new

**Comment by maguid28** [comment]
I am having the same error. Can you explain your resolution a bit more?
