### ISSUE TITLE
AssertionError: Generated entrypoint command that was not bash

### ISSUE THREAD

**Issue by mikemcelligott** [AntonOsika/gpt-engineer#172]
I'm generating a node/express back-end and a flutter app front-end, but I keep getting the same error message (as written above).  I know GPT-4 is capable of writing code in various different languages but I'm not sure how to enable support for those languages in the python code.  I've also noticed that filenames frequently have open or close braces in them for some reason with this stack.

Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/Users/michael/Projects/gpt-engineer/gpt_engineer/main.py", line 63, in <module>
    app()

  File "/Users/michael/Projects/gpt-engineer/gpt_engineer/main.py", line 58, in chat
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "/Users/michael/Projects/gpt-engineer/gpt_engineer/steps.py", line 174, in gen_entrypoint
    assert lang in [
           ^^^^^^^^^

AssertionError: Generated entrypoint command that was not bash

**Comment by patillacode** [comment]
Many changes have been applied since you posted this, give the latest version a try.

If you wish to reopen the issue please do following the new issue template.
