### ISSUE TITLE
`identity/setup` not found

### ISSUE THREAD

**Issue by pjz** [AntonOsika/gpt-engineer#230]
```
Traceback (most recent call last):
  File "/home/pj/src/gpt-engineer/.direnv/python-3.10.6/bin/gpt-engineer", line 8, in <module>
    sys.exit(execute())
  File "/home/pj/src/gpt-engineer/.direnv/python-3.10.6/lib/python3.10/site-packages/gpt_engineer/main.py", line 49, in execute
    app()
  File "/home/pj/src/gpt-engineer/.direnv/python-3.10.6/lib/python3.10/site-packages/gpt_engineer/main.py", line 44, in chat
    messages = step(ai, dbs)
  File "/home/pj/src/gpt-engineer/.direnv/python-3.10.6/lib/python3.10/site-packages/gpt_engineer/steps.py", line 58, in run_clarified
    ai.fsystem(setup_sys_prompt(dbs)),
  File "/home/pj/src/gpt-engineer/.direnv/python-3.10.6/lib/python3.10/site-packages/gpt_engineer/steps.py", line 9, in setup_sys_prompt
    return dbs.identity['setup'] + '\nUseful to know:\n' + dbs.identity['philosophy']
  File "/home/pj/src/gpt-engineer/.direnv/python-3.10.6/lib/python3.10/site-packages/gpt_engineer/db.py", line 14, in __getitem__
    with open(self.path / key, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pj/src/gpt-engineer/identity/setup'
```
The obvious workaround of touching identity/setup seems to work, but I'm wondering if someone forgot to either add the setup file to git or remove the use of it from steps.py.

**Comment by juarezjl** [comment]
got the same issue so I just clone the repo instead :P

**Comment by AntonOsika** [comment]
`pip install -e .`
