### ISSUE TITLE
Running "gpt-engineer $(project)" results to: TypeError: 'type' object is not subscriptable in python versions <3.9

### ISSUE THREAD

**Issue by SlamChillz** [AntonOsika/gpt-engineer#253]
```
Traceback (most recent call last):
  File "/home/python/open-source/gpt-engineer/venv/bin/gpt-engineer", line 5, in <module>
    from gpt_engineer.main import app
  File "/home/python/open-source/gpt-engineer/gpt_engineer/main.py", line 10, in <module>
    from gpt_engineer.ai import AI
  File "/home/python/open-source/gpt-engineer/gpt_engineer/ai.py", line 8, in <module>
    class AI:
  File "/home/python/open-source/gpt-engineer/gpt_engineer/ai.py", line 40, in AI
    def next(self, messages: list[dict[str, str]], prompt=None):
TypeError: 'type' object is not subscriptable
```
**Python 3.8.10**

**Comment by SlamChillz** [comment]
@patillacode please permit me make a PR to fix this issue
