### ISSUE TITLE
Issue in steps "qa" key error

### ISSUE THREAD

**Issue by abhikkr** [AntonOsika/gpt-engineer#280]
**YOU MAY DELETE THE ENTIRE TEMPLATE BELOW.**

# Issue Template

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. When running the code qa key error happening from steps.py
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by lixiaofei123** [comment]
same error

**Comment by lixiaofei123** [comment]
Traceback (most recent call last):

  File "/home/jovyan/work/langchain/modelio/gpt-engineer/venv/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/home/jovyan/work/langchain/modelio/gpt-engineer/gpt_engineer/main.py", line 61, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "/home/jovyan/work/langchain/modelio/gpt-engineer/gpt_engineer/steps.py", line 30, in clarify
    messages = [ai.fsystem(dbs.identity["qa"])]
                           ~~~~~~~~~~~~^^^^^^

  File "/home/jovyan/work/langchain/modelio/gpt-engineer/gpt_engineer/db.py", line 18, in __getitem__
    raise KeyError(key)

KeyError: 'qa'

**Comment by feherstefan** [comment]
same error for me as well
Traceback (most recent call last):

  File "/opt/homebrew/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/gpt_engineer/main.py", line 61, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/gpt_engineer/steps.py", line 30, in clarify
    messages = [ai.fsystem(dbs.identity["qa"])]
                           ~~~~~~~~~~~~^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/gpt_engineer/db.py", line 18, in __getitem__
    raise KeyError(key)

KeyError: 'qa'

**Comment by mikle7** [comment]
Same error

**Comment by BANG88** [comment]
copy to where

**Comment by sallar** [comment]
having the same issue

**Comment by feherstefan** [comment]
> Copy https://github.com/AntonOsika/gpt-engineer/tree/main/identity into your path

hi, could you be a tad more explicit, please? i copied the dir to my path, exported as path as well, but I still get the same error

**Comment by cclemon2143** [comment]
same error

**Comment by cclemon2143** [comment]
same error 🤔

Traceback (most recent call last):

  File "/Users/zhuangyicheng/opt/anaconda3/envs/gptEngigeer/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())

  File "/Users/zhuangyicheng/opt/anaconda3/envs/gptEngigeer/lib/python3.9/site-packages/gpt_engineer/main.py", line 61, in main
    messages = step(ai, dbs)

  File "/Users/zhuangyicheng/opt/anaconda3/envs/gptEngigeer/lib/python3.9/site-packages/gpt_engineer/steps.py", line 30, in clarify
    messages = [ai.fsystem(dbs.identity["qa"])]

  File "/Users/zhuangyicheng/opt/anaconda3/envs/gptEngigeer/lib/python3.9/site-packages/gpt_engineer/db.py", line 18, in __getitem__
    raise KeyError(key)

KeyError: 'qa'

**Comment by tfevens** [comment]
Any help for us Windows scrubs is appreciated as well!

Traceback (most recent call last):

  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)

  File "C:\Python39\Scripts\gpt-engineer.exe\__main__.py", line 7, in <module>
    sys.exit(app())

  File "c:\python39\lib\site-packages\gpt_engineer\main.py", line 61, in main
    messages = step(ai, dbs)

  File "c:\python39\lib\site-packages\gpt_engineer\steps.py", line 30, in clarify
    messages = [ai.fsystem(dbs.identity["qa"])]

  File "c:\python39\lib\site-packages\gpt_engineer\db.py", line 18, in __getitem__
    raise KeyError(key)

KeyError: 'qa'

**Comment by hansun11** [comment]
having the same issue

**Comment by patillacode** [comment]
If you wish to reopen the issue please do following the new issue template. (I mean actually filling it with the required information)

**Comment by DrMemoryFish** [comment]
did you all do this step:

Create an empty folder. If inside the repo, you can run:
cp -r projects/example/ projects/my-new-project
Fill in the main_prompt file in your new folder
Run: gpt-engineer projects/my-new-project


inside of "my-new-project" you need to provide your prompt. 
then go to the main folder, and run the above command.

**Comment by IbragimovDP** [comment]
Hello!
🔥Next helps me:
1. Remove my own file main_prompt
2. Copy the same file from example folder
3. Change and save it without .txt

The same problem was due to the main_prompt file format. It turned out to be .txt by accident, but it should be without .txt as in the example in the repo.

**Comment by feherstefan** [comment]
https://github.com/AntonOsika/gpt-engineer/issues/291#issuecomment-1601998510
I opened a ticket here and the problem is now solved, refer to this solution and if the problem is solved for you as well please close the issue so that people could find the solution quickly
