### ISSUE TITLE
Errors in simple run

### ISSUE THREAD

**Issue by eliashanna9** [AntonOsika/gpt-engineer#290]
Hey, running the same as in the demo, creating a Go DSL parser and got the following error:

```
Assuming that the codebase is a Go project, the following commands can be used to install dependencies and run the codebase:

1. Install dependencies:
go mod download

2. Run the codebase:
go run *.go

Note: The above commands assume that all the Go files are in the same directory and that the main function is in one of the files. If the main function is in a different file, replace `*.go` with the name of the file containing the main function.
Traceback (most recent call last):

  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)

  File "/root/dev/gpt-engineer/gpt_engineer/main.py", line 49, in <module>
    app()

  File "/root/dev/gpt-engineer/gpt_engineer/main.py", line 45, in chat
    messages = step(ai, dbs)

  File "/root/dev/gpt-engineer/gpt_engineer/steps.py", line 106, in execute_workspace
    messages = gen_entrypoint(ai, dbs)

  File "/root/dev/gpt-engineer/gpt_engineer/steps.py", line 141, in gen_entrypoint
    [[lang, command]] = parse_chat(messages[-1]["content"])

ValueError: too many values to unpack (expected 1)

```

Running in an ubuntu container on a M1 Mac

**Comment by AntonOsika** [comment]
Is solved now
