### ISSUE TITLE
error running for the first time

### ISSUE THREAD

**Issue by Mr0sari0** [AntonOsika/gpt-engineer#346]
I am trying to run for the first time and I keep getting an error.

When I run:
gpt-engineer projects/my-new-project

I get:
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\AppData\Local\Programs\Python\Python310\Scripts\gpt-engineer.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'gpt_engineer'

I appreciate all the help and any suggestions you might have. 
Thank you,
Miguel

**Comment by TharakaUmayanga** [comment]
You need to run as following 
`python -m gpt_engineer.main my-new-project`

**Comment by Mr0sari0** [comment]
Thank you I got it working I had to uninstall all the pythons reinstall it and update the path

**Comment by SumitKumarDev10** [comment]
I think you have forgot to install the library.
