### ISSUE TITLE
api

### ISSUE THREAD

**Issue by Nuhannmiller** [AntonOsika/gpt-engineer#352]
**YOU MAY DELETE THE ENTIRE TEMPLATE BELOW.**

# Issue Template

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Nuhannmiller** [comment]
C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe "E:/GITHUB files/gpt-engineer-main/gpt-engineer-main/gpt_engineer/main.py"
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')': /v1/models/gpt-3.5-turbo-16k
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')': /v1/models/gpt-3.5-turbo-16k
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:997)


The above exception was the direct cause of the following exception:


urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 874, in urlopen
    return self.urlopen(

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 874, in urlopen
    return self.urlopen(

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/models/gpt-3.5-turbo-16k (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 598, in request_raw
    result = _thread_context.session.request(

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)

requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/models/gpt-3.5-turbo-16k (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))))


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "E:\GITHUB files\gpt-engineer-main\gpt-engineer-main\gpt_engineer\main.py", line 64, in <module>
    app()

  File "E:\GITHUB files\gpt-engineer-main\gpt-engineer-main\gpt_engineer\main.py", line 45, in main
    ai = AI(

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gpt_engineer\ai.py", line 15, in __init__
    openai.Model.retrieve(model)

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\api_resource.py", line 20, in retrieve
    instance.refresh(request_id=request_id, request_timeout=request_timeout)

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\api_resource.py", line 32, in refresh
    self.request(

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\openai_object.py", line 179, in request
    response, stream, api_key = requestor.request(

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 290, in request
    result = self.request_raw(

  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 611, in request_raw
    raise error.APIConnectionError(

openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/models/gpt-3.5-turbo-16k (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))))

Process finished with exit code 1
JUST ABOVE,IS THERE SOMEONE CAN HELP ME ??

**Comment by stagsz** [comment]
Same issue

**Comment by LopeKinz** [comment]
Country?
