### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by pshapiro** [AntonOsika/gpt-engineer#368]
I've tried it with both dev and stable release. Running on a virtualenv. It doesn't matter if I use my own prompt or the example prompt. I get this error:

```
paul$ gpt-engineer projects/example
Traceback (most recent call last):
  File "/Users/paul/Documents/Development/gpt-engineer-0.0.5/gpteng/bin/gpt-engineer", line 5, in <module>
    from gpt_engineer.main import app
  File "/Users/paul/Documents/Development/gpt-engineer-0.0.5/gpteng/lib/python3.8/site-packages/gpt_engineer/main.py", line 9, in <module>
    from gpt_engineer import steps
  File "/Users/paul/Documents/Development/gpt-engineer-0.0.5/gpteng/lib/python3.8/site-packages/gpt_engineer/steps.py", line 19, in <module>
    Step = TypeVar("Step", bound=Callable[[AI, DBs], list[dict]])
TypeError: 'type' object is not subscriptable
```
Any ideas?

**Comment by psluja** [comment]
I guess it's already fixed in source gpt_engineer/steps.py. Look at line 19, there should be List[dict] not list[dict]. Also imports should be fixed as well. 
Package version is not up to date.
