### ISSUE TITLE
KeyError: 'main_prompt'

### ISSUE THREAD

**Issue by Venkateshvenki404224** [AntonOsika/gpt-engineer#372]
## Error 
```
└─# gpt-engineer projects/my-new-project            
Traceback (most recent call last):

  File "/home/kali/Desktop/gpt-engineer/venv/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/home/kali/Desktop/gpt-engineer/gpt_engineer/main.py", line 60, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "/home/kali/Desktop/gpt-engineer/gpt_engineer/steps.py", line 37, in clarify
    user = dbs.input["main_prompt"]
           ~~~~~~~~~^^^^^^^^^^^^^^^

  File "/home/kali/Desktop/gpt-engineer/gpt_engineer/db.py", line 21, in __getitem__
    raise KeyError(key)

KeyError: 'main_prompt'
```

**Comment by mOrGaNCrYpTo** [comment]
Same error

**Comment by AntonOsika** [comment]
Need more info to debug. Did you follow inspections etc

**Comment by jayo2005** [comment]
I have the same issue. Using Linux Mint. Fresh install nothing installed only gpt-engineer. What do you mean by inspections?

**Comment by dohsimpson** [comment]
If you are following the example, you should have a file called `main_prompt` instead of `prompt`. The program by default searches for that file.

**Comment by chaitanyanarukulla** [comment]
same issue ==  KeyError: 'main_prompt'
This was working  for me yesterday , this morning i pulled new changes from main b  and now i get  KeyError: 'main_prompt'
