### ISSUE TITLE
When making assumptions, generates error

### ISSUE THREAD

**Issue by lduperval** [AntonOsika/gpt-engineer#383]
I created a prompt (in main_prompt, as it seems to be the new default behavior). Ran and got the error trace below:

(letting gpt-engineer make its own assumptions)

INFO:openai:error_code=None error_message="{'role': 'user', 'content': 'Make your own assumptions and state them explicitly before starting'} is not of type 'string' - 'messages.3.content'" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
Traceback (most recent call last):

  File "C:\Users\ME\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "C:\Users\ME\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)

  File "C:\Users\ME\anaconda3\Scripts\gpt-engineer.exe\__main__.py", line 7, in <module>
    sys.exit(app())

  File "C:\Users\ME\Documents\gpt-engineer\gpt_engineer\main.py", line 62, in main
    messages = step(ai, dbs)

  File "C:\Users\ME\Documents\gpt-engineer\gpt_engineer\steps.py", line 66, in clarify
    messages = ai.next(

  File "C:\Users\ME\Documents\gpt-engineer\gpt_engineer\ai.py", line 47, in next
    response = openai.ChatCompletion.create(

  File "C:\Users\ME\anaconda3\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)

  File "C:\Users\ME\anaconda3\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(

  File "C:\Users\ME\anaconda3\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)

  File "C:\Users\ME\anaconda3\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(

  File "C:\Users\ME\anaconda3\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(

openai.error.InvalidRequestError: {'role': 'user', 'content': 'Make your own assumptions and state them explicitly before starting'} is not of type 'string' - 'messages.3.content'

**Comment by JwabeNero** [comment]
Same

**Comment by kneeki** [comment]
Pressing `c` consistently returns the following

```text
Clarification needed:
- What should the modal window look like when an error occurs?

(answer in text, or "c" to move on)
c

(letting gpt-engineer make its own assumptions)

INFO:openai:error_code=None error_message="{'role': 'user', 'content': 'Make your own assumptions and state them explicitly before starting'} is not of type 'string' - 'messages.3.content'" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
Traceback (most recent call last):

  File "/home/dave/work/presentpal/gpt-engineer/venv/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/home/dave/work/presentpal/gpt-engineer/gpt_engineer/main.py", line 63, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "/home/dave/work/presentpal/gpt-engineer/gpt_engineer/steps.py", line 66, in clarify
    messages = ai.next(
               ^^^^^^^^

  File "/home/dave/work/presentpal/gpt-engineer/gpt_engineer/ai.py", line 47, in next
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/dave/work/presentpal/gpt-engineer/venv/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/dave/work/presentpal/gpt-engineer/venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^

  File "/home/dave/work/presentpal/gpt-engineer/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/dave/work/presentpal/gpt-engineer/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(

  File "/home/dave/work/presentpal/gpt-engineer/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(

openai.error.InvalidRequestError: {'role': 'user', 'content': 'Make your own assumptions and state them explicitly before starting'} is not of type 'string' - 'messages.3.content'
```

**Comment by jayo2005** [comment]
Same issue

**Comment by SumitKumarDev10** [comment]
**A Limitation Of AI**
I think that the code is asking you to make assumptions because it is not able to make it on its own.

**Comment by ATheorell** [comment]
Closing this stale issue, since it is unclear whether it still is a problem and in which configurations it is a problem.
