### ISSUE TITLE
openai.error.AuthenticationError: No API key provided. 

### ISSUE THREAD

**Issue by marianotir** [AntonOsika/gpt-engineer#405]
I run the following: 

1. conda create env gpt
2. conda activate env 
3. git clone into folder
4. pip install gpt-engineer
5. and then setx OPENAI_API_KEY api_key because I use windows. Then I get the message SUCCESS: Specified value was saved. 
6. then I run gpt-engineer>gpt-engineer projects/my_project 

and I get the error 
`Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\marianota\.conda\envs\gpt-engineer\Scripts\gpt-engineer.exe\__main__.py", line 7, in <module>
    sys.exit(app())
             ^^^^^

  File "C:\Users\marianota\.conda\envs\gpt-engineer\Lib\site-packages\gpt_engineer\main.py", line 47, in main
    model = fallback_model(model)
            ^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\marianota\.conda\envs\gpt-engineer\Lib\site-packages\gpt_engineer\ai.py", line 58, in fallback_model
    openai.Model.retrieve(model)

  File "C:\Users\marianota\.conda\envs\gpt-engineer\Lib\site-packages\openai\api_resources\abstract\api_resource.py", line 20, in retrieve
    instance.refresh(request_id=request_id, request_timeout=request_timeout)

  File "C:\Users\marianota\.conda\envs\gpt-engineer\Lib\site-packages\openai\api_resources\abstract\api_resource.py", line 32, in refresh
    self.request(

  File "C:\Users\marianota\.conda\envs\gpt-engineer\Lib\site-packages\openai\openai_object.py", line 172, in request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\marianota\.conda\envs\gpt-engineer\Lib\site-packages\openai\api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\marianota\.conda\envs\gpt-engineer\Lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(

openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
.`

**Comment by buziyborni** [comment]
you can manually insect it in the ai.py just after the logger

**Comment by marianotir** [comment]
using openai.api_key = 'api key' ?

**Comment by marianotir** [comment]
it works
