### ISSUE TITLE
What's this problem?

### ISSUE THREAD

**Issue by xiaoyupzy** [AntonOsika/gpt-engineer#416]
### Failure Logs

C:\gpt-engineer>python gpt_engineer\main.py projects\renamefiles
Traceback (most recent call last):

  File "C:\gpt-engineer\gpt_engineer\main.py", line 71, in <module>
    app()

  File "C:\gpt-engineer\gpt_engineer\main.py", line 47, in main
    model = fallback_model(model)

  File "C:\gpt-engineer\gpt_engineer\ai.py", line 58, in fallback_model
    openai.Model.retrieve(model)

  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\openai\api_resources\abstract\api_resource.py", line 20, in retrieve
    instance.refresh(request_id=request_id, request_timeout=request_timeout)

  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\openai\api_resources\abstract\api_resource.py", line 32, in refresh
    self.request(

  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\openai\openai_object.py", line 179, in request
    response, stream, api_key = requestor.request(

  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\openai\api_requestor.py", line 288, in request
    result = self.request_raw(

  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\openai\api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(

  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")

ValueError: check_hostname requires server_hostname

**Comment by AntonOsika** [comment]
Need more info to debug, seems like you overrode BASE_URL?
