### ISSUE TITLE
NOT RECOGNISED

### ISSUE THREAD

**Issue by saiggs** [AntonOsika/gpt-engineer#441]
![image](https://github.com/AntonOsika/gpt-engineer/assets/132798161/c8449173-8632-4950-9b68-00c1807dcc37)

**Comment by noxiouscardiumdimidium** [comment]
depends on how you installed and when...  could be an env/venv needs to be activated. or if you installed the git pull ontop of the old pip (or vice versa ) that'll brick it (pip uninstall gpt_engineer ; pip install gpt_engineer) or you did just the first stage of the dev install, but never did the next step 
![Thu Jun 29 03:50:17 AM CDT 2023](https://github.com/AntonOsika/gpt-engineer/assets/115574840/b7edbc32-e9ba-4ce4-ab22-10c1abaf9197)

**Comment by saiggs** [comment]
i did pip install -e, and all other things in correct order

**Comment by noxiouscardiumdimidium** [comment]
after the `-e` its a period, not a comma. with a comma, it might have installed all the deps in your home folder or some other part of root. the period tells it "starting from this location" like launching a command that needs `./` . not putting the period is one of several things that would throw that error

**Comment by saiggs** [comment]
I have used period

**Comment by saiggs** [comment]
INFO:openai:error_code=model_not_found error_message="The model 'gpt-4' does not exist" error_param=model error_type=invalid_request_error message='OpenAI API error received' stream_error=False
Model gpt-4 not available for provided API key. Reverting to gpt-3.5-turbo. Sign up for the GPT-4 wait list here: https://openai.com/waitlist/gpt-4-api

INFO:openai:error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\Saiteja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\gpt-engineer.exe\__main__.py", line 7, 
in <module>
    sys.exit(app())
             ^^^^^

  File "C:\Users\Saiteja\gpt-engineer\gpt_engineer\main.py", line 64, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "C:\Users\Saiteja\gpt-engineer\gpt_engineer\steps.py", line 55, in clarify
    messages = ai.next(messages, user_input)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Saiteja\gpt-engineer\gpt_engineer\ai.py", line 37, in next
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Saiteja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Saiteja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^

  File "C:\Users\Saiteja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Saiteja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(

  File "C:\Users\Saiteja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(

openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Comment by jenspacito** [comment]
Yes im here.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jenspacito** [comment]
Hey Anton, great ist funktion.
Thx 4 your support. Im really new here. Im so happy.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dabbinavo** [comment]
@saiggs : Did you resolve your issue with `You exceeded your current quota, please check your plan and billing details`?
There are other users (me including), which are affected by this. See #547 .

**Comment by AntonOsika** [comment]
Housekeeping: Closing stale issues.
