### ISSUE TITLE
Statistics: collection of learnings did not work as intended

### ISSUE THREAD

**Issue by eleijonmarck** [AntonOsika/gpt-engineer#462]
this line is expecting 1 arguments, might need to specify the `open_ssl` version

https://github.com/AntonOsika/gpt-engineer/blob/main/gpt_engineer/collect.py#L39

## Expected Behavior
Collection of data should have been submitted

## Current Behavior
What is the current behavior?

To help gpt-engineer learn, please answer 3 questions:
```python
Did the generated code run at all? y/n/u(ncertain): y
Did the generated code do everything you wanted? y/n/u(ncertain): y
Thank you
Traceback (most recent call last):

  File "/opt/homebrew/Caskroom/miniconda/base/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())

  File "/Users/eleijonmarck/dev/gpt-engineer/gpt_engineer/main.py", line 67, in main
    collect_learnings(model, temperature, steps, dbs)

  File "/Users/eleijonmarck/dev/gpt-engineer/gpt_engineer/collect.py", line 31, in collect_learnings
    model, temperature, steps, dbs, steps_file_hash=steps_file_hash()

  File "/Users/eleijonmarck/dev/gpt-engineer/gpt_engineer/collect.py", line 39, in steps_file_hash
    return hashlib.sha256(content.encode("utf-8"), usedforsecurity=False).hexdigest()

TypeError: openssl_sha256() takes at most 1 argument (2 given)
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. generate project
2. run code
3. CTRL+C (end the program running)
4. answer questions

pyproject.toml
```toml
[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "gpt-engineer"
version = "0.0.7"
description = "Specify what you want it to build, the AI asks for clarification, and then builds it."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  'black == 23.3.0',
  'click >= 8.0.0',
  'mypy == 1.3.0',
  'openai == 0.27.8',
  'pre-commit == 3.3.3',
  'pytest == 7.3.1',
  'ruff == 0.0.272',
  'termcolor==2.3.0',
  'typer >= 0.3.2',
  'rudder-sdk-python == 2.0.2',
  'dataclasses-json == 0.5.7',
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "License :: OSI Approved :: MIT License",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.scripts]
gpt-engineer = 'gpt_engineer.main:app'

[tool.setuptools]
packages = ["gpt_engineer"]

[tool.ruff]
select = ["F", "E", "W", "I001"]
line-length = 90
show-fixes = false
target-version = "py311"
task-tags = ["TODO", "FIXME"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[project.urls]
"Homepage" = "https://github.com/AntonOsika/gpt-engineer"
"Bug Tracker" = "https://github.com/AntonOsika/gpt-engineer/issues"

[tool.ruff.isort]
known-first-party = []
known-third-party = []
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
combine-as-imports = true
split-on-trailing-comma = false
lines-between-types = 1

[tool.black]
line-length = 90
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
(
  /(
      \.direnv
    | \.eggs
    | \.git
    | \.tox
    | \.venv
    | _build
    | build
    | dist
    | venv
  )/
)
'''
```

**Comment by eleijonmarck** [comment]
Did not have time right now to look into this. But will work on this if possible

**Comment by AntonOsika** [comment]
Thanks for filing! I think you have an older version of python, should work now. Please reopen if it doesn't work!
