### ISSUE TITLE
No python files get written unless I use the example

### ISSUE THREAD

**Issue by Ryan-be** [AntonOsika/gpt-engineer#550]
**YOU MAY DELETE THE ENTIRE TEMPLATE BELOW.**

## Expected Behavior

When I run Gbt engineer writes python/code files to disk 

## Current Behavior

when GBT engineer runs it will write all_output.txt to disk but no code/python files get written to disk. but when i run the example it writes files to disk just fine with out any errors. 

## Failure Information (for bugs)
This is the traceback i get (this is after all of the output has been written to all_output.txt
Traceback (most recent call last):

  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)

  File "C:\Users\<user>\PycharmProjects\gpt-engineer\venv\Scripts\gpt-engineer.exe\__main__.py", line 7, in <module>
    sys.exit(app())

  File "C:\Users\<user>\PycharmProjects\gpt-engineer\venv\lib\site-packages\gpt_engineer\main.py", line 64, in main
    messages = step(ai, dbs)

  File "C:\Users\<user>\PycharmProjects\gpt-engineer\venv\lib\site-packages\gpt_engineer\steps.py", line 156, in gen_clarified_code
    to_files(messages[-1]["content"], dbs.workspace)

  File "C:\Users\<user>\PycharmProjects\gpt-engineer\venv\lib\site-packages\gpt_engineer\chat_to_files.py", line 42, in to_files
    workspace[file_name] = file_content

  File "C:\Users\<user>\PycharmProjects\gpt-engineer\venv\lib\site-packages\gpt_engineer\db.py", line 36, in __setitem__
    full_path.write_text(val, encoding="utf-8")

  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1152, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:

  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,

OSError: [Errno 22] Invalid argument: 'C:\\Users\\<user>\\PycharmProjects\\gpt-engineer\\projects\\my-new-project\\workspace\\content:'

**Comment by Ryan-be** [comment]
Sorry, just solved it. it was folder permissions issues.
