### ISSUE TITLE
RuntimeError: ('Message exceeds %skb limit. (%s)', AFTER it asks me to run the code

### ISSUE THREAD

**Issue by stlorenz** [AntonOsika/gpt-engineer#582]
I am running a quite complex prompt to create a python app with a PSQL DB backend. I already have the whole DB schema ready and pasted it into the prompt. 

## Expected Behavior

the app is created according to my prompt.

## Current Behavior
Only a part of the files are created, then it asks me to run the code which fails for non-related reasons and then shows the error message"
RuntimeError: ('Message exceeds %skb limit. (%s)', '32', '{\'integrations\': {\'All\': True}, \'anonymousId\': None, \'properties\': {\'model\': \'gpt-3.5-turbo\', \'temperature\': 0.1, \'steps\': \'["clarify", "gen_clarified_code", "gen_entrypoint", "execute_entrypoint", "human_review"]\', \'steps_file_hash\': \'\', \'prompt\' 
REMAINING OUTPUT of gpt engineer. 

Error seems to be in the analytics page

  File "/home/stefan/.local/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/home//code/gpt-engineer/gpt_engineer/main.py", line 61, in main
    collect_learnings(model, temperature, steps, dbs)

  File "/home/code/gpt-engineer/gpt_engineer/collect.py", line 28, in collect_learnings
    send_learning(learnings)

  File "/home/code/gpt-engineer/gpt_engineer/collect.py", line 17, in send_learning
    rudder_analytics.track(

  File "/home/.local/lib/python3.11/site-packages/rudderstack/analytics/__init__.py", line 53, in track
    _proxy('track', *args, **kwargs)

  File "/home/.local/lib/python3.11/site-packages/rudderstack/analytics/__init__.py", line 113, in _proxy
    fn(*args, **kwargs)

  File "/home/.local/lib/python3.11/site-packages/rudderstack/analytics/client.py", line 141, in track
    return self._enqueue(msg)
           ^^^^^^^^^^^^^^^^^^

  File "/home/.local/lib/python3.11/site-packages/rudderstack/analytics/client.py", line 279, in _enqueue
    raise RuntimeError('Message exceeds %skb limit. (%s)', str(int(MAX_MSG_SIZE / 1024)), str(msg))

UPDATE: confirmed related to Rudderstack, does not happen when you opt out

**Comment by danielrosly** [comment]
I have the same error in exactly the same context.

**Comment by pbharrin** [comment]
@danielrosly When was your code updated?  We pushed a fix for this on 8/18.  Let me know if you are still getting this error after the fix, otherwise I will close this issue.  

Here is the fix: https://github.com/AntonOsika/gpt-engineer/commit/803eb82362278b755127649e9bb5f385639a23ca

**Comment by danielrosly** [comment]
Error occurred for application that I installed using pip yesterday (`python -m pip install gpt-engineer`). I don't know which version it is as app doesn't print it.

**Comment by byeblack** [comment]
I just cloned the project from the main repository, and I still encounter the same problem after installation
`
During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "python\Scripts\gpt-engineer.exe\__main__.py", line 7, in <module>
    sys.exit(app())
             ^^^^^

  File "gpt-engineer\gpt_engineer\main.py", line 95, in main
    collect_learnings(model, temperature, steps, dbs)

  File "gpt-engineer\gpt_engineer\collect.py", line 71, in collect_learnings
    send_learning(learnings)

  File "gpt-engineer\gpt_engineer\collect.py", line 31, in send_learning
    rudder_analytics.track(

  File "python\Lib\site-packages\rudderstack\analytics\__init__.py", line 53, in track
    _proxy('track', *args, **kwargs)

  File "python\Lib\site-packages\rudderstack\analytics\__init__.py", line 113, in _proxy
    fn(*args, **kwargs)

  File "python\Lib\site-packages\rudderstack\analytics\client.py", line 141, in track
    return self._enqueue(msg)
           ^^^^^^^^^^^^^^^^^^

  File "python\Lib\site-packages\rudderstack\analytics\client.py", line 279, in _enqueue
    raise RuntimeError('Message exceeds %skb limit. (%s)', str(int(MAX_MSG_SIZE / 1024)), str(msg))
`

**Comment by ATheorell** [comment]
Closing this since it been on triage for 5 days. Let me know if anyone still has the issues and I reopen
