### ISSUE TITLE
Sweep: use_feedback crashes

### ISSUE THREAD

**Issue by NinoSkopac** [AntonOsika/gpt-engineer#610]
### Details

```bash
gpt-engineer --help                            
Usage: gpt-engineer [OPTIONS] [PROJECT_PATH] [MODEL]

Arguments:
  [PROJECT_PATH]  path  [default: projects/example]
  [MODEL]         model id string  [default: gpt-4]

Options:
  --temperature FLOAT             [default: 0.1]
  -s, --steps [default|benchmark|simple|tdd|tdd+|clarify|respec|execute_only|evaluate|use_feedback]
                                  decide which steps to run  [default:
                                  Config.DEFAULT]
  -v, --verbose
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.
  --help                          Show this message and exit.


% gpt-engineer --steps use_feedback projects/example
Traceback (most recent call last):

  File "/usr/local/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/Users/user/PhpstormProjects/gpt-engineer/gpt_engineer/main.py", line 57, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "/Users/user/PhpstormProjects/gpt-engineer/gpt_engineer/steps.py", line 250, in use_feedback
    ai.fassistant(dbs.workspace["all_output.txt"]),
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^

  File "/Users/user/PhpstormProjects/gpt-engineer/gpt_engineer/db.py", line 24, in __getitem__
    raise KeyError(f"File '{key}' could not be found in '{self.path}'")

KeyError: "File 'all_output.txt' could not be found in '/Users/user/PhpstormProjects/gpt-engineer/projects/example/workspace'"
```

<details>
<summary>Checklist</summary>

- [X] `gpt_engineer/steps.py`
> • In the 'use_feedback' function, replace 'all_output.txt' with the correct file name if it is a naming mismatch issue.
> • If the file is being created in a different location, update the path in 'dbs.workspace["all_output.txt"]' to point to the correct location.
> • If the 'all_output.txt' file is not being created in the previous steps, add the code to create this file before the 'use_feedback' step is called.

</details>

**Comment by kevinlu1248** [comment]
Looks like a matching error: we'll fix this.

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by AntonOsika** [comment]
@NinoSkopac did you first run without --use-feedback so that the codebase, to apply the feedback to, is generated?

**Comment by NinoSkopac** [comment]
Yes

**Comment by AntonOsika** [comment]
Housekeeping: Closing stale issues.

Feel free to open if problem persists on latest main branch.
