### ISSUE TITLE
Sweep: "Did the generated code do everything you wanted?" results in error.

### ISSUE THREAD

**Issue by lehcode** [AntonOsika/gpt-engineer#618]
### Details

Any answer results in the same error.

```bash
Did the generated code do everything you wanted? y/n/u(ncertain): y
Traceback (most recent call last):

  File "/home/dev/gpt-engineer/venv/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())

  File "/home/dev/gpt-engineer/gpt_engineer/main.py", line 87, in main
    collect_learnings(model, temperature, steps, dbs)

  File "/home/dev/gpt-engineer/gpt_engineer/collect.py", line 37, in collect_learnings
    send_learning(learnings)

  File "/home/dev/gpt-engineer/gpt_engineer/collect.py", line 26, in send_learning
    rudder_analytics.track(

  File "/home/dev/gpt-engineer/venv/lib/python3.10/site-packages/rudderstack/analytics/__init__.py", line 53, in track
    _proxy('track', *args, **kwargs)

  File "/home/dev/gpt-engineer/venv/lib/python3.10/site-packages/rudderstack/analytics/__init__.py", line 113, in _proxy
    fn(*args, **kwargs)

  File "/home/dev/gpt-engineer/venv/lib/python3.10/site-packages/rudderstack/analytics/client.py", line 141, in track
    return self._enqueue(msg)

  File "/home/dev/gpt-engineer/venv/lib/python3.10/site-packages/rudderstack/analytics/client.py", line 279, in _enqueue
    raise RuntimeError('Message exceeds %skb limit. (%s)', str(int(MAX_MSG_SIZE / 1024)), str(msg))
```

```bash
$ uname -a
Linux DUALBOOT 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ which python
/home/dev/gpt-engineer/venv/bin/python
```

```bash
python --version
Python 3.10.12
```

<details>
<summary>Checklist</summary>

- [X] `gpt_engineer/collect.py`
> • Modify the `send_learning` function to catch the `RuntimeError` exception. In the exception handler, split the learning data into smaller chunks and send each chunk separately to Rudder Analytics.

- [X] `gpt_engineer/learning.py`
> • Modify the `extract_learning` function to reduce the size of the learning data. This can be done by removing unnecessary data or reducing the precision of the data.

</details>

**Comment by AntonOsika** [comment]
Should work now on main branch. Please lmk if it happens again.
