### ISSUE TITLE
Sweep: WARNING: learning too big, removing some parts. Please report if this results in a crash.

### ISSUE THREAD

**Issue by lehcode** [AntonOsika/gpt-engineer#631]
### Details

When running `gpt-engineer -s improve_code` with numerous Python classes learning fails after .

```
WARNING: learning too big, removing some parts. Please report if this results in a crash.
Traceback (most recent call last):

  File "/home/dev/gpt-engineer/gpt_engineer/collect.py", line 57, in collect_learnings
    send_learning(learnings)

  File "/home/dev/gpt-engineer/gpt_engineer/collect.py", line 31, in send_learning
    rudder_analytics.track(

  File "/home/dev/gpt-engineer/venv/lib/python3.10/site-packages/rudderstack/analytics/__init__.py", line 53, in track
    _proxy('track', *args, **kwargs)

  File "/home/dev/gpt-engineer/venv/lib/python3.10/site-packages/rudderstack/analytics/__init__.py", line 113, in _proxy
    fn(*args, **kwargs)

  File "/home/dev/gpt-engineer/venv/lib/python3.10/site-packages/rudderstack/analytics/client.py", line 141, in track
    return self._enqueue(msg)

  File "/home/dev/gpt-engineer/venv/lib/python3.10/site-packages/rudderstack/analytics/client.py", line 279, in _enqueue
    raise RuntimeError('Message exceeds %skb limit. (%s)', str(int(MAX_MSG_SIZE / 1024)), str(msg))
```

<details>
<summary>Checklist</summary>

- [X] `gpt_engineer/collect.py`
> • Modify the `send_learning` function to split the learning data into smaller chunks if its size exceeds the maximum limit of 32kb. Use a loop to iterate over the chunks and send each chunk separately to RudderStack.
> • Implement a helper function `split_learning_data` that takes the learning data and the maximum size limit as input and returns a list of chunks. Each chunk should be a valid learning data and its size should not exceed the maximum size limit.
> • In the `split_learning_data` function, use a suitable data structure (like a list or a dictionary) to store the chunks. Use a loop to iterate over the learning data and add data to a chunk until its size reaches the maximum limit. Then, start a new chunk and continue the process until all data is divided into chunks.
> • In the `send_learning` function, handle the case where even after splitting, a chunk of learning data is still larger than the size limit. In such a case, further split the chunk or remove less important parts of the data until it fits within the size limit.

</details>

**Comment by pbharrin** [comment]
Closing this as it was fixed on 8/18
