### ISSUE TITLE
AssertionError: Please put your prompt in the file `prompt` in the project directory

### ISSUE THREAD

**Issue by nulone** [AntonOsika/gpt-engineer#636]
Getting same error even if try to execute program just by typing "gpt-engineer" in the console

**Comment by tasdawg** [comment]
What error are you getting?
you have to do the following, make a new directory called example2, inside the example2 directory make a file called prompt. in this file you but your prompt example, "Make a snakes game, use HTML, javascript. use house keeping and seperate each ocmponent into there own files". once this is done then use "python3 main.py example2/".

**Comment by Kalimero31** [comment]
Got the same issue, "get_prompt()" method seems not to work whereas i followed the instructions above. 
It just creates an empty archives folder

**Comment by Kalimero31** [comment]
PS C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer> python main.py exemple2
Traceback (most recent call last):

  File "C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer\main.py", line 67, in <module>
    app()

  File "C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer\main.py", line 57, in main    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer\steps.py", line 61, in clarify
    user_input = get_prompt(dbs)
                 ^^^^^^^^^^^^^^^

  File "C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer\steps.py", line 28, in get_prompt
    "prompt" in dbs.input or "main_prompt" in dbs.input
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^

AssertionError: Please put your prompt in the file `prompt` in the project directory

PS C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer>

**Comment by pbharrin** [comment]
Is there a file called: "prompt" in the example2 directory?  It should just be called: prompt, not prompt.txt.  You can create it with Notepad.

**Comment by Kalimero31** [comment]
I think so
![image](https://github.com/AntonOsika/gpt-engineer/assets/113331848/db15a7be-486a-4b28-ad8a-24c927d45f24)

**Comment by suganyapriya** [comment]
PS C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer> python main.py exemple2
Traceback (most recent call last):

File "C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer\main.py", line 67, in
app()

File "C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer\main.py", line 57, in main messages = step(ai, dbs)
^^^^^^^^^^^^^

File "C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer\steps.py", line 61, in clarify
user_input = get_prompt(dbs)
^^^^^^^^^^^^^^^

File "C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer\steps.py", line 28, in get_prompt
"prompt" in dbs.input or "main_prompt" in dbs.input
^^^^^^^^^^^^^^^^^^^^^^^^^^

AssertionError: Please put your prompt in the file prompt in the project directory

PS C:\Users\jimit\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_engineer>

same getting error

**Comment by Kalimero31** [comment]
yes

**Comment by pbharrin** [comment]
There was an error like this in the past #528.  See the solution there.  
I can look into a fix that will also look for `prompt.txt` or `prompt`.

**Comment by calebcauthon** [comment]
@nulone try `gpt-engineer .` <-- (period there)

**Comment by ATheorell** [comment]
Is this error persisting @nulone ? Was .txt the problem?
