### ISSUE TITLE
Not handled out of request count, save the state instead.

### ISSUE THREAD

**Issue by logunovFGP** [AntonOsika/gpt-engineer#713]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Expected Behavior

gpt-engineer not crashing, saving the state and proposes continue later

## Current Behavior

GPT-engineer crashes in endless loop attempting to request the data. The whole conversation is not cached so I need to perform input from scratch and waste credits to re-input information.

## Failure Information

GPT-4 LLM.

### Steps to Reproduce

Just attempt to give large input when gpt-engineer has lots of questions, I spent 30 mins answering questions. 
### Failure Logs

Nothing more to clarify.
INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues..
INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues..
INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues..
INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues..
INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues..
INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Scripts\gpt-engineer.exe\__main__.py", line 7, in <module>
    sys.exit(app())
             ^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\gpt_engineer\main.py", line 96, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\gpt_engineer\steps.py", line 199, in gen_clarified_code
    messages = ai.next(messages, dbs.preprompts["generate"], step_name=curr_fn())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\gpt_engineer\ai.py", line 173, in next
    response = self.llm(messages, callbacks=callsbacks)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\langchain\chat_models\base.py", line 551, in __call__
    generation = self.generate(
                 ^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\langchain\chat_models\base.py", line 309, in generate
    raise e

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\langchain\chat_models\base.py", line 299, in generate
    self._generate_with_cache(

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\langchain\chat_models\base.py", line 446, in _generate_with_cache
    return self._generate(
           ^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\langchain\chat_models\openai.py", line 334, in _generate
    for chunk in self._stream(

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\langchain\chat_models\openai.py", line 305, in _stream
    for chunk in self.completion_with_retry(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\langchain\chat_models\openai.py", line 278, in completion_with_retry
    return _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Logun\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Logun\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\langchain\chat_models\openai.py", line 276, in _completion_with_retry
    return self.client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(

  File "G:\REPOS\PROJECTS\aviator-game-test\.venv\Lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(

openai.error.RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-8JuGfI1rBZ1rbbaeM3CSLawd on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.

**Comment by logunovFGP** [comment]
To be clear, the main issue here that I have answered already, but gpt-engineer not handled exception lead to the context not saved, so when I started the project again, it started from the same question, which means:
- double money spent on API
- double time spent on answering question (less, if they saved and you expect the crash)
- no guarantee it won't crash again after feeling-in the data.

**Comment by ATheorell** [comment]
Thanks for the report! First of all:

@lukaspetersson (as reviewer of ai.py) do we need to add a catch somewhere for RateLimitError?

Generally: We are actively working on making gpt-engineer simpler, with shorter prompts etc, for example PR #733 @logunovFGP

**Comment by lukaspetersson** [comment]
> @lukaspetersson (as reviewer of ai.py) do we need to add a catch somewhere for RateLimitError?

#741

**Comment by ATheorell** [comment]
Closing with the merging of #741 . Let us know if the error persists @logunovFGP
