### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 436: character maps to <undefined>

### ISSUE THREAD

**Issue by RiccardoRomagnoli** [AntonOsika/gpt-engineer#758]
## Expected Behavior

gpt-engineer "path" -i command to work properly

## Current Behavior

Error after "Press enter to proceed with modifications."

### Steps to Reproduce

windows
python 3.9 

### Failure Logs

Traceback (most recent call last):

  File "C:\tools\Anaconda3\envs\gpteng\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "C:\tools\Anaconda3\envs\gpteng\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)

  File "C:\tools\Anaconda3\envs\gpteng\Scripts\gpt-engineer.exe\__main__.py", line 7, in <module>
    sys.exit(app())

  File "C:\tools\Anaconda3\envs\gpteng\lib\site-packages\gpt_engineer\main.py", line 96, in main
    messages = step(ai, dbs)

  File "C:\tools\Anaconda3\envs\gpteng\lib\site-packages\gpt_engineer\steps.py", line 360, in improve_existing_code
    files_info = get_code_strings(dbs.input)  # this only has file names not paths

  File "C:\tools\Anaconda3\envs\gpteng\lib\site-packages\gpt_engineer\chat_to_files.py", line 113, in get_code_strings
    file_data = file.read()

  File "C:\tools\Anaconda3\envs\gpteng\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 436: character maps to <undefined>

<details open>
<summary>Checklist</summary>

- [X] ``gpt_engineer/core/chat_to_files.py:get_code_strings`` ✅ Commit [`83c9784`](https://github.com/AntonOsika/gpt-engineer/commit/83c97847c89a1c4336f8c824a6b34aa54de17f33)
</details>

**Comment by ATheorell** [comment]
My impression is that this error is related to the specific file that is read. Would you be able to share it somehow, preferably on your github?

**Comment by RiccardoRomagnoli** [comment]
it is working just fine in WSL

**Comment by ATheorell** [comment]
That is great! But, if we are to solve this problem without WSL, it would be great if we can reproduce it. UnicodeDecodeError sounds like it is related to the file. It would be great if you can try it again after the recent refactor and repost the stack trace (the code has changed quite a lot).

**Comment by AntonOsika** [comment]
This easily happens if you have a folder that contains non text files in `file_list.txt` and that folder contains cache files etc

**Comment by AntonOsika** [comment]
We should try to fix the error message!

Like "file xyz is not of text format, please make sure gpt-engineer doesn't read it"

**Comment by TheoMcCabe** [comment]
Fix is out here: 

https://github.com/AntonOsika/gpt-engineer/pull/801
