### ISSUE TITLE
I keep facing error that breaks the execution of the program everytime I try to prompt is to build something like a password generator

### ISSUE THREAD

**Issue by thesmartcoder7** [AntonOsika/gpt-engineer#789]
```
pydantic.v1.error_wrappers.ValidationError: 1 validation error for AIMessage
is_chunk
  unexpected value; permitted: False (type=value_error.const; given=True; permitted=(False,))
  
  
 for context . . .  here is the whole traceback
 
 Traceback (most recent call last):

  File "/home/samuel/.local/share/virtualenvs/test-zF55lqY5/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/home/samuel/.local/share/virtualenvs/test-zF55lqY5/lib/python3.11/site-packages/gpt_engineer/main.py", line 96, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "/home/samuel/.local/share/virtualenvs/test-zF55lqY5/lib/python3.11/site-packages/gpt_engineer/steps.py", line 192, in gen_clarified_code
    messages = AI.deserialize_messages(dbs.logs[clarify.__name__])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/samuel/.local/share/virtualenvs/test-zF55lqY5/lib/python3.11/site-packages/gpt_engineer/ai.py", line 216, in deserialize_messages
    return list(messages_from_dict(json.loads(jsondictstr)))  # type: ignore
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/samuel/.local/share/virtualenvs/test-zF55lqY5/lib/python3.11/site-packages/langchain/schema/messages.py", line 351, in messages_from_dict
    return [_message_from_dict(m) for m in messages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/samuel/.local/share/virtualenvs/test-zF55lqY5/lib/python3.11/site-packages/langchain/schema/messages.py", line 351, in <listcomp>
    return [_message_from_dict(m) for m in messages]
            ^^^^^^^^^^^^^^^^^^^^^

  File "/home/samuel/.local/share/virtualenvs/test-zF55lqY5/lib/python3.11/site-packages/langchain/schema/messages.py", line 331, in _message_from_dict
    return AIMessage(**message["data"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/samuel/.local/share/virtualenvs/test-zF55lqY5/lib/python3.11/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)

  File "/home/samuel/.local/share/virtualenvs/test-zF55lqY5/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error

pydantic.v1.error_wrappers.ValidationError: 1 validation error for AIMessage
is_chunk
  unexpected value; permitted: False (type=value_error.const; given=True; permitted=(False,))
```

**Comment by ATheorell** [comment]
Interesting! For reproduction purposes, can you provide:
1) the gpt-engineer commit that you are running
2) the which LLM you are running (for example chatGPT4)
3) the prompt that leads to this problem (at least most of the time).

**Comment by ATheorell** [comment]
Thanks for the info!
The version on pypi is quite outdated and will be updated soon. Can you try and pip install the version on the current master branch?
To do this, pip uninstall gpt-engineer, then clone the repo, navigate to the repo with a terminal and type pip install . .

**Comment by thesmartcoder7** [comment]
Thank you very much. This worked
