### ISSUE TITLE
KeyError: "File 'some/dir/models.py' could not be found in 'C:\\Users\\Asus\\gptengineer\\crm\\projects\\example'"

### ISSUE THREAD

**Issue by nusretocakturk** [AntonOsika/gpt-engineer#876]
## Expected Behvior
To work normally as it was working normally before.

## Current Behavior

it always gives this or similiar error I dont understand these paths are not exist , ıdk where it came u with these.... KeyError: "File 'some/dir/models.py' could not be found in 'C:\\Users\\Asus\\gptengineer\\crm\\projects\\example'"
## Failure Information

KeyError: "File 'some/dir/models.py' could not be found in 'C:\\Users\\Asus\\gptengineer\\crm\\projects\\example'" - used conda , used normal terminal
### Steps to Reproduce

If possible, provide detailed steps for reproducing the issue.

well , I was just running normally on my project folder , for some time later it started to give me these errors thats all, 

### Failure Logs

>>>>>>> updated
```Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\ProgramData\miniconda3\envs\myenv\Scripts\gpt-engineer.exe\__main__.py", line 7, in <module>
    sys.exit(app())
             ^^^^^

  File "C:\ProgramData\miniconda3\envs\myenv\Lib\site-packages\gpt_engineer\cli\main.py", line 169, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "C:\ProgramData\miniconda3\envs\myenv\Lib\site-packages\gpt_engineer\core\steps.py", line 588, in improve_existing_code
    overwrite_files_with_edits(messages[-1].content.strip(), dbs)

  File "C:\ProgramData\miniconda3\envs\myenv\Lib\site-packages\gpt_engineer\core\chat_to_files.py", line 220, in overwrite_files_with_edits
    apply_edits(edits, dbs.workspace)

  File "C:\ProgramData\miniconda3\envs\myenv\Lib\site-packages\gpt_engineer\core\chat_to_files.py", line 281, in apply_edits
    if workspace[filename].count(edit.before) > 1:
       ~~~~~~~~~^^^^^^^^^^

  File "C:\ProgramData\miniconda3\envs\myenv\Lib\site-packages\gpt_engineer\core\db.py", line 126, in __getitem__
    raise KeyError(f"File '{key}' could not be found in '{self.path}'")

KeyError: "File 'some/dir/models.py' could not be found in 'C:\\Users\\Asus\\gptengineer\\crm\\projects\\example'"


(myenv) C:\Users\Asus\gptengineer\gpt-engineer>

**Comment by sergeyktvg** [comment]
i am getting the same in improve mode, what was the fix?
