### ISSUE TITLE
Can't make it work.

### ISSUE THREAD

**Issue by VioletRaven** [AntonOsika/gpt-engineer#906]
After doing:
_Run gpte <project_dir> with a relative path to your folder
For example: gpte projects/my-new-project from the gpt-engineer directory root with your new folder in projects/_

I should be using the correct relative path and I get 

`Traceback (most recent call last):
  File "C:\Users\a.serrano\AppData\Local\pypoetry\Cache\virtualenvs\gpt-engineer-elTYTC0x-py3.9\Scripts\gpte", line 3, in <module>
    from gpt_engineer.applications.cli.main import app
  File "C:\Users\a.serrano\Desktop\Projects\fashion_creator\gpt-engineer\gpt_engineer\applications\cli\main.py", line 38, in <module>
    from gpt_engineer.applications.cli.cli_agent import CliAgent
  File "C:\Users\a.serrano\Desktop\Projects\fashion_creator\gpt-engineer\gpt_engineer\applications\cli\cli_agent.py", line 6, in <module>
    from gpt_engineer.core.base_execution_env import BaseExecutionEnv
  File "C:\Users\a.serrano\Desktop\Projects\fashion_creator\gpt-engineer\gpt_engineer\core\base_execution_env.py", line 7, in <module>
    class BaseExecutionEnv(ABC):
  File "C:\Users\a.serrano\Desktop\Projects\fashion_creator\gpt-engineer\gpt_engineer\core\base_execution_env.py", line 22, in BaseExecutionEnv
    def run(self, command: str, timeout: int | None = None) -> tuple[str, str, int]:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
(gpt-engineer-py3.9) C:\Users\a.serrano\Desktop\Projects\fashion_creator\gpt-engineer>gpte projects/fashion_creator
Traceback (most recent call last):
  File "C:\Users\a.serrano\AppData\Local\pypoetry\Cache\virtualenvs\gpt-engineer-elTYTC0x-py3.9\Scripts\gpte", line 3, in <module>
    from gpt_engineer.applications.cli.main import app
  File "C:\Users\a.serrano\Desktop\Projects\fashion_creator\gpt-engineer\gpt_engineer\applications\cli\main.py", line 38, in <module>
    from gpt_engineer.applications.cli.cli_agent import CliAgent
  File "C:\Users\a.serrano\Desktop\Projects\fashion_creator\gpt-engineer\gpt_engineer\applications\cli\cli_agent.py", line 6, in <module>
    from gpt_engineer.core.base_execution_env import BaseExecutionEnv
  File "C:\Users\a.serrano\Desktop\Projects\fashion_creator\gpt-engineer\gpt_engineer\core\base_execution_env.py", line 7, in <module>
    class BaseExecutionEnv(ABC):
  File "C:\Users\a.serrano\Desktop\Projects\fashion_creator\gpt-engineer\gpt_engineer\core\base_execution_env.py", line 22, in BaseExecutionEnv
    def run(self, command: str, timeout: int | None = None) -> tuple[str, str, int]:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`

What should I do?

**Comment by ErikBjare** [comment]
There's another issue where this has been reported before.

The workaround is to use Python 3.10 or higher.

**Comment by similato87** [comment]
Hi @VioletRaven, the project is now compatible with Python 3.9. If you still want to continue using Python 3.9, fetch the existing project and it will run.

**Comment by ATheorell** [comment]
as @similato87 says, this should now be fixed
